# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33600ab9d27bc2352efb8b9065d0d9a7d30a32519fcf404fd0831336fe0aa70816b914d0d8d98629be6862c6229c9552106b12274d9048eaad101ea526b84840

test:
  secret_key_base: 43af649b72330043730d897f98489275b5d8fc8a9256954f25f4ace4d3f048ce4bdbef628996ddbb11e36fcc4d901114aa9ebc21734ea0e96b84f69a58e6d687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
